<%--基础样式--%>
<link href="${pageContext.request.contextPath}/static/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
<%--第三方样--%>
<link href="${pageContext.request.contextPath}/static/plugins/datatable/css/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css"/>
<link href="${pageContext.request.contextPath}/static/css/public/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/select2/css/select2.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/My97DatePicker/skin/WdatePicker.css" rel="stylesheet" type="text/css" />
<%--自定义样--%>
<link href="${pageContext.request.contextPath}/static/css/public/googosoft.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/iconfont.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/public-list.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/newTableByThead.css" rel="stylesheet" type="text/css" />
<style type="text/css">
	.overflow{
		overflow:auto;
		margin-left:15px;
		margin-right:15px;
	}
	.total{
		margin-top:10px;
		font-weight: bold;
	}
	.icon-chaxun{
		top:5px;
	}
.form-control[readonly]{
background-color: white;
}
input{
 border: 1px solid #ccc;
    border-radius: 4px;
    line-height: 28px;
    padding-left: 6px;
}
</style>

