<link href="${pageContext.request.contextPath}/static/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/iconfont.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/googosoft.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css"/>
<link href="${pageContext.request.contextPath}/static/css/public/public-manager.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/fileinput/fileinput.css"media="all"rel="stylesheet"type="text/css"/>
<link href="${pageContext.request.contextPath}/static/plugins/select2/css/select2.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/My97DatePicker/skin/WdatePicker.css" rel="stylesheet" type="text/css" />


