<%--基础脚本--%>
<script src="${pageContext.request.contextPath}/static/javascript/jquery/jquery.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/bootstrap/bootstrap.min.js"></script>
<%--第三方脚本plugins--%>
<script src="${pageContext.request.contextPath}/static/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/datatable/js/dataTables.bootstrap.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/datetimepicker/bootstrap-datetimepicker.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/My97DatePicker/WdatePicker.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/validator/bootstrapValidator.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/suggest/jquerySuggest.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/select2/js/select2.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/select2/js/i18n/zh-CN.js"></script>
<%--自定义脚本--%>
<script src="${pageContext.request.contextPath}/static/javascript/public/public-window.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/public-js.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/download.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/translation-js.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/columnsExp.js"></script>

<script>
var search_wid = "170px";
</script>