<script src="${pageContext.request.contextPath}/static/javascript/jquery/jquery.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/datetimepicker/bootstrap-datetimepicker.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/My97DatePicker/WdatePicker.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/echarts.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/echarts.googosoft.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/default.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/dark.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/infographic.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/macarons.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/roma.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/shine.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/theme/vintage.js"></script>

<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/map/china.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/map/shandong.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/echarts/map/world.js"></script>


<script src="${pageContext.request.contextPath}/static/javascript/public/public-json.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/public-window.js"></script>
<script src="${pageContext.request.contextPath}/static/javascript/public/public-js.js"></script>
<script type="text/javascript" src="${pageContext.request.contextPath}/static/plugins/suggest/jquerySuggest.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/select2/js/select2.js"></script>
<script src="${pageContext.request.contextPath}/static/plugins/select2/js/i18n/zh-CN.js"></script>
