<link href="${pageContext.request.contextPath}/static/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/iconfont.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/googosoft.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/css/public/public-draw.css" rel="stylesheet" type="text/css" />
<link href="${pageContext.request.contextPath}/static/plugins/datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css"/>
<link href="${pageContext.request.contextPath}/static/plugins/select2/css/select2.css" rel="stylesheet" type="text/css" />