<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/plugins/ext/ext-all.css"/>
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/css/public/font-awesome.css" />
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/css/bootstrap/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/static/css/public/googosoft.css" />
<style type="text/css">
	.input-group {
		padding: 10px;
	}
	.btn.btn-default {
		padding: 3px 10px;
		height: 25px !important;
	}
	.tool-fix{
		display:none;
	}
</style>